### PR TITLE
get correct position of inline widget

### PR DESCRIPTION
**Pull request by wisewrong**
1. convert with editingDowncast; 
2. get correct position of inline widget.

### CODE REVIEW

**Comment by antoniolucasnobar** [comment]
Hello @wisewrong 

Thanks for your contribution! Would you mind to explain to me what "get correct position of inline widget" means? What is happening? Maybe add some images, so I can understand. Which version of ckeditor are you using?

I really did not understand your changes. You changed the `_find` method to something very similar to the https://github.com/antoniolucasnobar/ckeditor5-find-replace/blob/v0.2.0/src/findCommand.js#L48-L60

The main difference is that there was no callback back then (because there was no `getText` function either)

This approach was changed because @YueHui found an problem with formatted text (italic or bold, for example). In this case, the search did not work as expected; Please take a look at: https://github.com/antoniolucasnobar/ckeditor5-find-replace/pull/5

As you did not use the `getText` result, I think what you did may break what was done in pull #5 

Could you please help me understand?

Have a nice day!
A. Lucas

**Comment by wisewrong** [comment]
Thanks for the reply.

Here is an official example about "inline widget": [Implementing an inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html).

When the document contains an inline widget, FindReplace will get the wrong position, like this:
avatar
If the image is not loaded, you can check [here](https://github.com/wisewrong/ckeditor5-find-replace/blob/wise.wrong_demo/example/bug.png)

In addition, I added a [demo branch](https://github.com/wisewrong/ckeditor5-find-replace/tree/wise.wrong_demo) to the fork project. You can run it with "npm run dev" to reproduce the bug.

Have a nice day!

**Comment by antoniolucasnobar** [comment]
Hello @wisewrong , thanks for the demo branch. It will help.

I see the problem, but as I told in my previous comment, your solution breaks what was done in #5 . So we have to find a way to work with both scenarios.

I also noted that the search plugin do not find any text inside the inline plugin (as it is not a text node). If you have any ideas how to overcome this, please let me know.

**Comment by wisewrong** [comment]
Hello @antoniolucasnobar , I agree with you.

I'll close this PR and try to find the best solution.

Best Regards.

**Comment by antoniolucasnobar** [comment]
Hello @wisewrong 

I did not see your message. I worked on this PR to make it work with inline widgets and, at the same time, work with formatted text.

My idea is to glue toghether only the text in textNodes (this solves the formatted text isssue). Then, when it finds a non text node (it can be an inline widget or the end of the paragraph), I get the indices in the grouped text. Then, I use the first textNode of this group to get the startOffset and parent (this solves the inline widget problem).

I wonder if you could check it out my changes and see if it works as intended. I tested locally and, for me, it works just fine. I did not changed the code in the demo branch, only in this one used here in PR.

@YueHui I changed what you did in PR #5. Besides this problem @wisewrong found, I noted errors if the text uses the blockquote plugin. I think it is because the nested structure: blockquote -> paragraph -> text. I changed the approach to solve both problems. if you can test it out in your scenarios, it would be great. But I tested here and it worked just fine with formatted text.

I know this method needs to be split, but I will not do it while we are working in this PR.

I have a few questions, if you do not mind to answer:
- Why to use the `editingDowncast`? I read already the architecture introduction, but I can not figure out which one to use. 
- Which browser are you using? I noted the Match case option is not aligned with its checkbox. I use Firefox on Linux and it looks fine (you can see the pictures in the README).

PS.: I still do not know how to find any text inside the inline plugin. Maybe we should look to the view instead of the model... I would need help to do this, as this plugin is based on the model to search.

If we can not fix this now, we can try to do it this later, in another issue.

**Comment by wisewrong** [comment]
Hello @antoniolucasnobar 

Thanks for your  work, I will check it out at once. Before that, I will answer your question first.

1.  `downcast` contains `dataDowncast` and `editingDowncast `, `editor.getData()` will export the conversion result of `dataDowncast`, like this (or [here](https://github.com/wisewrong/ckeditor5-find-replace/blob/wise.wrong_demo/example/bug2.png)):
avatar
2. I use Google Chrome Version 90. It's easy to fix  this problem by add `align-items: center;` to `.ck.ck-labeled-field-view>.ck.ck-labeled-field-view__input-wrapper`.

**Comment by antoniolucasnobar** [comment]
thanks for your explanation! It helped me understand this difference between those `editingDowncast` and `dataDowncast`.
I fixed the css with your suggestion.

**Comment by wisewrong** [comment]
Hello @antoniolucasnobar 

I did a test with your commit, it works fine, I think this is the best result so far.

For the inline widget, I think its content should not be modified externally.

Take the Placeholder plugin as an example, its content has been set when it is inserted, users do not want it to be replaced by FindSearch or others. Maybe they need to be found, but it is not a strong feature.

So I think it’s a good idea to keep the current commit (^ _ ^)

**Comment by antoniolucasnobar** [comment]
Released version 0.3.1

thanks for your contribution @wisewrong !

**Pull request merged**
